[package]
name = "webclientfulltextsearch"
version = "0.4.0"
authors = ["suzuki0keiichi <suzuki0keiichi@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.87"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
console_error_panic_hook = { version = "0.1.6", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
serde_json = "1.0"

[profile.release]
opt-level = "s"
lto = true
